#include <sstream>

#include "gtest/gtest.h"
#include "src/mappers/province_mapper/province_mapper.hpp"

namespace mappers
{

TEST(MappersProvinceMapperTests, MappingsDefaultToEmpty)  // NOLINT : clang-tidy doens't like gtest
{
   std::stringstream input;
   const ProvinceMapper mapper(input);

   ASSERT_TRUE(mapper.GetCK3ToEU5().empty());
   ASSERT_TRUE(mapper.GetEU5Locations(1).empty());
}

TEST(MappersProvinceMapperTests, ProvinceMapsToLocation)  // NOLINT : clang-tidy doens't like gtest
{
   std::stringstream input;
   input << "0.0.0 = {\n";
   input << "link = { ck3 = 8297 eu5 = abiy_addi }\n";
   input << "}";
   const ProvinceMapper mapper(input);

   ASSERT_EQ(1, mapper.GetEU5Locations(8297).size());
   ASSERT_EQ("abiy_addi", mapper.GetEU5Locations(8297).front());
}

TEST(MappersProvinceMapperTests, OneProvinceToSeveralLocations)  // NOLINT : clang-tidy doens't like gtest
{
   std::stringstream input;
   input << "0.0.0 = {\n";
   input << "link = { autogenerated = yes ck3 = 3806 eu5 = abrahamtelke eu5 = solt }\n";
   input << "}";
   const ProvinceMapper mapper(input);

   ASSERT_EQ(2, mapper.GetEU5Locations(3806).size());
   ASSERT_EQ(1, mapper.GetCK3Provinces("solt").size());
   ASSERT_EQ(3806, mapper.GetCK3Provinces("solt").front());
}

TEST(MappersProvinceMapperTests, SeveralProvincesToOneLocation)  // NOLINT : clang-tidy doens't like gtest
{
   std::stringstream input;
   input << "0.0.0 = {\n";
   input << "link = { autogenerated = yes ck3 = 8025 ck3 = 8026 eu5 = abengourou }\n";
   input << "}";
   const ProvinceMapper mapper(input);

   ASSERT_EQ(2, mapper.GetCK3Provinces("abengourou").size());
   ASSERT_EQ("abengourou", mapper.GetEU5Locations(8025).front());
   ASSERT_EQ("abengourou", mapper.GetEU5Locations(8026).front());
}

TEST(MappersProvinceMapperTests, TriangulationPairsAreIgnored)  // NOLINT : clang-tidy doens't like gtest
{
   std::stringstream input;
   input << "0.0.0 = {\n";
   input << "triangulation_pair = { srcX = 7039 srcY = 1668 dstX = 13098 dstY = 2603 }\n";
   input << "link = { ck3 = 8297 eu5 = abiy_addi }\n";
   input << "}";
   const ProvinceMapper mapper(input);

   ASSERT_EQ(1, mapper.GetCK3ToEU5().size());
   ASSERT_EQ("abiy_addi", mapper.GetEU5Locations(8297).front());
}

TEST(MappersProvinceMapperTests, OneSidedLinksAreSkipped)  // NOLINT : clang-tidy doens't like gtest
{
   // A CK3 wasteland with no EU5 counterpart, or an EU5 location with nothing in CK3.
   std::stringstream input;
   input << "0.0.0 = {\n";
   input << "link = { ck3 = 999 }\n";
   input << "link = { eu5 = orphan_location }\n";
   input << "link = { ck3 = 8297 eu5 = abiy_addi }\n";
   input << "}";
   const ProvinceMapper mapper(input);

   ASSERT_EQ(1, mapper.GetCK3ToEU5().size());
   ASSERT_TRUE(mapper.GetEU5Locations(999).empty());
   ASSERT_TRUE(mapper.GetCK3Provinces("orphan_location").empty());
}

TEST(MappersProvinceMapperTests, OnlyTheFirstVersionBlockIsUsed)  // NOLINT : clang-tidy doens't like gtest
{
   std::stringstream input;
   input << "0.0.0 = {\n";
   input << "link = { ck3 = 8297 eu5 = abiy_addi }\n";
   input << "}\n";
   input << "1.0.0 = {\n";
   input << "link = { ck3 = 1 eu5 = somewhere_else }\n";
   input << "}";
   const ProvinceMapper mapper(input);

   ASSERT_EQ(1, mapper.GetCK3ToEU5().size());
   ASSERT_TRUE(mapper.GetEU5Locations(1).empty());
}

}  // namespace mappers
