#ifndef MAPPERS_PROVINCE_MAPPER_H
#define MAPPERS_PROVINCE_MAPPER_H

#include <filesystem>
#include <istream>
#include <map>
#include <string>
#include <vector>

namespace mappers
{

// Maps CK3 provinces (barony level, the IDs in map_data/definition.csv) onto EU5 locations, from
// province_mappings.txt at the repository root.
//
//    link = { autogenerated = yes ck3 = 8025 ck3 = 8026 eu5 = abengourou }
//
// A link may carry several of each, since the two games' maps do not line up one to one. The file
// also holds triangulation_pair entries used to align the two map projections when the mappings
// were generated; they are not needed at conversion time and are ignored here.
//
// Only a single version block is supported, matching CK3toEU4: the file contains one 0.0.0 = { }.
class ProvinceMapper
{
  public:
   ProvinceMapper() = default;
   explicit ProvinceMapper(std::istream& input_stream);
   explicit ProvinceMapper(const std::filesystem::path& file_path);

   // Empty when the province has no EU5 counterpart.
   [[nodiscard]] const std::vector<std::string>& GetEU5Locations(long long ck3_province) const;
   [[nodiscard]] const std::vector<long long>& GetCK3Provinces(const std::string& eu5_location) const;

   [[nodiscard]] const auto& GetCK3ToEU5() const { return ck3_to_eu5_; }
   [[nodiscard]] const auto& GetEU5ToCK3() const { return eu5_to_ck3_; }

  private:
   void ParseMappings(std::istream& input_stream);
   void ParseVersion(std::istream& input_stream);

   std::map<long long, std::vector<std::string>> ck3_to_eu5_;
   std::map<std::string, std::vector<long long>> eu5_to_ck3_;
};

}  // namespace mappers

#endif  // MAPPERS_PROVINCE_MAPPER_H
